<?php
namespace App\Repositories\Note;

use App\Models\Auth\auth;
use Exception;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model as EloquentModel;
use phpDocumentor\Reflection\Types\Expression;
use Shamaseen\Repository\Utility\AbstractRepository as AbstractRepository;
use App\Models\Note\note;

/**
 * Class noteRepository.
 *
 * @extends AbstractRepository<note>
 */
class noteRepository extends AbstractRepository
{
    public array $with = [];

    /**
     * @return string
     */
    public function getModelClass(): string
    {
        return note::class;
    }




    public function create(array $data = [], int | Exception $user_id = new Exception): EloquentModel
    {
        $data['user_id']= $user_id ;
        return parent::create($data); // TODO: Change the autogenerated stub
    }



}
